; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

;#define UPGRADE
;#define WIN9X

#define MAJOR_VER "1"
#define MINOR_VER "5"
#define RELEASE_VER "4"


[Setup]
AppName=ZMatrix
AppMutex=ZMatrix
AppVerName=ZMatrix {#MAJOR_VER}.{#MINOR_VER}.{#RELEASE_VER}
AppPublisher=Payalord
AppPublisherURL=https://payalord.github.io/ZMatrix/
AppSupportURL=https://github.com/payalord/ZMatrix/issues
AppUpdatesURL=https://payalord.github.io/ZMatrix/
AppVersion={#MAJOR_VER}.{#MINOR_VER}.{#RELEASE_VER}
DefaultDirName={pf}\ZMatrix
DefaultGroupName=ZMatrix
AllowNoIcons=yes
#ifdef WIN9X
MinVersion=4.0,0
#else
MinVersion=0,6.1
#endif
PrivilegesRequired=poweruser
LicenseFile=LICENSE.TXT
#ifdef WIN9X
SourceDir=..\Distro9x
#else
SourceDir=..\DistroNT
#endif
ShowTasksTreeLines=yes

#ifdef WIN9X
  #ifdef UPGRADE
  OutputBaseFilename=ZMatrixSetup9x_{#MAJOR_VER}_{#MINOR_VER}_{#RELEASE_VER}_Upgrade
  #else
  OutputBaseFilename=ZMatrixSetup9x_{#MAJOR_VER}_{#MINOR_VER}_{#RELEASE_VER}
  #endif
#else
  #ifdef UPGRADE
  OutputBaseFilename=ZMatrixSetupNT_{#MAJOR_VER}_{#MINOR_VER}_{#RELEASE_VER}_Upgrade
  #else
  OutputBaseFilename=ZMatrixSetupNT_{#MAJOR_VER}_{#MINOR_VER}_{#RELEASE_VER}
  #endif
#endif

[Components]
Name: "main"; Description: "Main Program Files"; Types: full compact custom; Flags: fixed
Name: "screensaver"; Description: "Screensaver Component"; Types: full

[Files]
Source: "matrix.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: main
#ifndef WIN9X
Source: "JapaneseSet.txt"; DestDir: "{app}"; Flags: ignoreversion; Components: main
#endif
Source: "MatrixCodeFontSet.txt"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "default.cfg"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "Config.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "zsMatrix.dll"; DestDir: "{app}"; Flags: ignoreversion regserver; Components: main
Source: "MsgHook.dll"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "Matrix Code Font.ttf"; DestDir: "{fonts}"; FontInstall: "Matrix Code Font"; Flags: uninsneveruninstall ignoreversion; Components: main
Source: "ORIGINALREADME.md"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "BUILDING.md"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "docs\USER_GUIDE.md"; DestDir: "{app}\docs"; Flags: ignoreversion; Components: main
Source: "docs\DEVELOPMENT.md"; DestDir: "{app}\docs"; Flags: ignoreversion; Components: main
Source: "docs\SCRIPTS.md"; DestDir: "{app}\docs"; Flags: ignoreversion; Components: main
Source: "Matrix Code Font ReadMe.txt"; DestDir: "{app}"; Flags: ignoreversion; Components: main
Source: "LICENSE.TXT"; DestDir: "{app}"; Components: main

Source: "ScreenSaver\ZMatrixSS.scr"; DestDir: "{win}"; Flags: ignoreversion; Components: screensaver


[INI]
Filename: "{win}\ZMatrixSS.ini"; Section: "ZMatrixSS"; Key: "MatrixCommandLine"; String: "{app}\matrix.exe"
Filename: "{app}\ZMatrix.ini"; Section: "ZMatrix"; Key: "SetAsScreenSaverWhileRunning"; String: "true"; Tasks: setsswhilerunning
;Filename: "{app}\default.cfg"; Section: "General"; Key: "PriorityClass"; String: "HIGH_PRIORITY_CLASS"; Tasks: default_high_priority
;Filename: "{app}\default.cfg"; Section: "General"; Key: "PriorityClass"; String: "ABOVE_NORMAL_PRIORITY_CLASS"; Tasks: default_above_normal_priority
;Filename: "{app}\default.cfg"; Section: "General"; Key: "PriorityClass"; String: "NORMAL_PRIORITY_CLASS"; Tasks: default_normal_priority
;Filename: "{app}\default.cfg"; Section: "General"; Key: "PriorityClass"; String: "BELOW_NORMAL_PRIORITY_CLASS"; Tasks: default_below_normal_priority
;Filename: "{app}\default.cfg"; Section: "General"; Key: "PriorityClass"; String: "IDLE_PRIORITY_CLASS"; Tasks: default_idle_priority

Filename: "{app}\default.cfg"; Section: "Text"; Key: "CharSet"; String: "0,1"; Check: FontDoesntExist
Filename: "{app}\default.cfg"; Section: "Text"; Key: "FontName"; String: "MS Serif"; Check: FontDoesntExist

[Icons]
Name: "{group}\ZMatrix"; Filename: "{app}\matrix.exe"; WorkingDir: "{app}"
Name: "{group}\ZMatrix Help"; Filename: "{app}\matrix.exe"; Parameters: "/help"; WorkingDir: "{app}"
Name: "{group}\ZMatrix Homepage"; Filename: "https://payalord.github.io/ZMatrix/"
Name: "{group}\ReadMe"; Filename: "{app}\matrix.exe"; Parameters: "/readme"; WorkingDir: "{app}"
Name: "{group}\LICENSE"; Filename: "{app}\LICENSE.TXT"
Name: "{group}\Uninstall ZMatrix"; Filename: "{uninstallexe}"
Name: "{userstartup}\ZMatrix"; Filename: "{app}\matrix.exe"; WorkingDir: "{app}"; Tasks: autostart\user
Name: "{commonstartup}\ZMatrix"; Filename: "{app}\matrix.exe"; WorkingDir: "{app}"; Tasks: autostart\common

[Tasks]
Name: autostart; Description: "Automatic startup"; GroupDescription: "Automatic Startup Options:"
Name: autostart\user; Description: "Automatic startup for &current user only"; GroupDescription: "Automatic Startup Options:"; Flags: exclusive
Name: autostart\common; Description: "Automatic startup for &all users"; GroupDescription: "Automatic Startup Options:"; Flags: exclusive unchecked

;Name: default_high_priority; Description: "High Priority"; GroupDescription: "Default Program Priority:"; Flags: exclusive unchecked
;Name: default_above_normal_priority; Description: "Above Normal Priority"; GroupDescription: "Default Program Priority:"; Flags: exclusive unchecked
;Name: default_normal_priority; Description: "Normal Priority"; GroupDescription: "Default Program Priority:"; Flags: exclusive unchecked
;Name: default_below_normal_priority; Description: "Below Normal Priority"; GroupDescription: "Default Program Priority:"; Flags: exclusive unchecked
;Name: default_idle_priority; Description: "Idle Priority (recommended)"; GroupDescription: "Default Program Priority:"; Flags: exclusive

Name: setsswhilerunning; Description: "Always set as &screensaver while running"; GroupDescription: "Screensaver Options:"; Flags: unchecked

[Run]
Filename: "{app}\matrix.exe"; Description: "Launch ZMatrix"; Flags: nowait postinstall skipifsilent
Filename: "{app}\matrix.exe"; Parameters: "/readme"; Description: "View the ZMatrix readme"; Flags: nowait postinstall skipifsilent unchecked

[InstallDelete]
Type: files; Name: "{app}\ZMatrixHelp.chm"
Type: files; Name: "{app}\ZMatrixHelp.chw"

[UninstallDelete]
Type: files; Name: "{win}\ZMatrixSS.ini"
Type: files; Name: "{app}\ZMatrix.ini"
Type: dirifempty; Name: "{app}"

[Code]

var
  RemoveUserSettings: Boolean;
  UserSettingsPath: String;

function FontDoesntExist(): Boolean;
var
  TempResult : Boolean;
begin
  TempResult := FileExists(ExpandConstant('{fonts}') + '\Matrix Code Font.ttf');
  Result := not TempResult;
end;

function RemoveSettingsFile(const Name: String): Boolean;
var
  Path: String;
begin
  Path := AddBackslash(UserSettingsPath) + Name;
  Result := True;
  if FileOrDirExists(Path) then
  begin
    Result := DeleteFile(Path);
    if Result then
      Log('Removed user settings: ' + Path)
    else
      Log('Could not remove user settings: ' + Path);
  end;
end;

function RemoveSettingsFiles(): Boolean;
var
  FindRec: TFindRec;
begin
  Result := False;
  if not DirExists(UserSettingsPath) then
  begin
    Result := True;
    Exit;
  end;
  if not FindFirst(UserSettingsPath, FindRec) then Exit;
  try
    // Do not follow a profile directory redirected through a link or junction.
    if (FindRec.Attributes and FILE_ATTRIBUTE_REPARSE_POINT) <> 0 then
    begin
      Log('Retained redirected settings directory: ' + UserSettingsPath);
      Exit;
    end;
  finally
    FindClose(FindRec);
  end;
  Result := True;
  if not RemoveSettingsFile('ZMatrix.cfg') then Result := False;
  if not RemoveSettingsFile('ZMatrixScreenSaver.cfg') then Result := False;
  if not RemoveSettingsFile('ZMatrixMisc.cfg') then Result := False;
  if not RemoveSettingsFile('Audio.cfg') then Result := False;
  // Remove only an empty directory; named presets and other files are retained.
  RemoveDir(UserSettingsPath);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    RemoveUserSettings := False;
    UserSettingsPath := ExpandConstant('{userappdata}\.ZMatrix');
    if not UninstallSilent() and DirExists(UserSettingsPath) then
      RemoveUserSettings := SuppressibleMsgBox(
        'Also remove ZMatrix settings for Windows account "' + GetUserNameString() + '"?' + #13#10#13#10 +
        UserSettingsPath + #13#10#13#10 +
        'This resets animation, audio reaction and screensaver preferences.' + #13#10 +
        'Saved presets and other Windows accounts are kept.' + #13#10#13#10 +
        'Choose No to keep your settings for a future installation.',
        mbConfirmation, MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES;
  end
  else if (CurUninstallStep = usPostUninstall) and RemoveUserSettings then
  begin
    if not RemoveSettingsFiles() then
      SuppressibleMsgBox('ZMatrix was uninstalled, but some settings could not be removed:' + #13#10#13#10 +
        UserSettingsPath + #13#10#13#10 +
        'Close any program using these files and remove the settings manually if needed.',
        mbError, MB_OK, IDOK);
  end;
end;
